Administracion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('propietario/', include('Apps.Propietario.urls')),
    path('visitante/', include('Apps.Visitante.urls')),
    path('areacomun/', include('Apps.AreaComun.urls')),
    path('reserva/', include('Apps.Reserva.urls')),
    path('usuario/', include('Apps.usuario.urls')),
    path('', LoginView.as_view(template_name='home/index.html'), name='home'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('accounts/login/', LoginView.as_view(template_name='usuario/login.html'), name='login'),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/Reserva/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from Apps.Reserva.views import RegistrarReserva, ListarReserva,\
    EditarReserva, EliminarReserva, DetalleReserva, BusquedaAjax

app_name = 'reserva'

urlpatterns = [
    path('listar/', login_required(ListarReserva.as_view()), name="listar_reserva"),
    path('detalle/<pk>/', login_required(DetalleReserva.as_view()), name="detalle_reserva"),
    path('registrar/', login_required(RegistrarReserva.as_view()), name="registrar_reserva"),
    path('editar/<pk>/', login_required(EditarReserva.as_view()), name="editar_reserva"),
    path('eliminar/<pk>/', login_required(EliminarReserva.as_view()), name="eliminar_reserva"),
    path('busquedaAjax/', login_required(BusquedaAjax.as_view()), name="busqueda_ajax"),
]

Apps/Visitante/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from Apps.Visitante.views import RegistrarVisitante, ListarVisitante,\
    EditarVisitante, EliminarVisitante, DetalleVisitante

app_name = 'visitante'

urlpatterns = [
    path('listar/', login_required(ListarVisitante.as_view()), name="listar_visitante"),
    path('detalle/<pk>/', login_required(DetalleVisitante.as_view()), name="detalle_visitante"),
    path('registrar/', login_required(RegistrarVisitante.as_view()), name="registrar_visitante"),
    path('editar/<pk>/', login_required(EditarVisitante.as_view()), name="editar_visitante"),
    path('eliminar/<pk>/', login_required(EliminarVisitante.as_view()), name="eliminar_visitante"),
]

Apps/Reserva/models.py
from django.db import models

# Create your models here.
from Apps.AreaComun.models import AreaComun
from Apps.Propietario.models import Propietario


class Reserva(models.Model):
    fecha = models.DateField(null=False)
    id_propietario = models.ForeignKey(Propietario, null=False, blank=False, on_delete=models.CASCADE)
    area_social = models.ManyToManyField(AreaComun, through='DetalleReserva', related_name='detalle_reserva')
    created_at = models.DateTimeField(auto_now_add=True)  # Optiene la fecha de registro automaticamente
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0}'.format(self.fecha)

class DetalleReserva(models.Model):
    id_reserva = models.ForeignKey(Reserva, on_delete=models.CASCADE)
    id_area_comun = models.ForeignKey(AreaComun, on_delete=models.CASCADE)
    hora = models.TimeField(null=False)
    tmp_uso = models.TimeField(null=False)

Apps/Reserva/forms.py
from django import forms
from Apps.Reserva.models import Reserva, DetalleReserva


class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = '__all__'
        labels = {
            'fecha': 'Fecha',
            'id_propietario': 'Propietario',
        }

        widgets = {
            'hora': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'hora'}),
            'tmp_uso': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'tmp_uso'}),
            'django.conf.locale.id': forms.TextInput(attrs={'class': 'form-control col-12 col-md-8', 'id': 'id_propietario'}),
        }

class DetalleReservaForm(forms.ModelForm):
    class Meta:
        model = DetalleReserva
        fields = '__all__'
        labels = {
            'id_reserva': 'ID Reserva',
            'id_area_comun': 'ID Area Comun',
            'hora': 'Hora',
            'tmp_uso': 'Timepo Uso',
        }

        widgets = {
            'id_reserva': forms.TextInput(attrs={'class': 'form-control col-12 col-md-8', 'id': 'id_reserva'}),
            'id_area_comun': forms.TextInput(attrs={'class': 'form-control col-12 col-md-8', 'id': 'id_area_comun'}),
            'hora': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'hora'}),
            'tmp_uso': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'tmp_uso'}),
        }

Apps/Reserva/views.py
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView

from Apps.AreaComun.models import AreaComun
from Apps.Reserva.models import Reserva
from Apps.Reserva.forms import ReservaForm, DetalleReservaForm


class ListarReserva(ListView):
    model = Reserva
    template_name = 'reserva/listar_reserva.html'
    context_object_name = 'reserva'
    paginate_by = 10

# class RegistrarReserva(CreateView):
#     model = Reserva
#     # fields = '__all__'
#     form_class = ReservaForm
#     template_name = 'reserva/registrar_reserva.html'
#     success_url = reverse_lazy('reserva:listar_reserva')

class RegistrarReserva(CreateView):
    model = Reserva
    # fields = '__all__'
    template_name = 'reserva/registrar_reserva.html'
    form_class = ReservaForm
    second_form_class = DetalleReservaForm
    success_url = reverse_lazy('reserva:listar_reserva')

    def get_context_data(self, **kwargs):
        context = super(RegistrarReserva, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
            return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            reserva = form.save(commit=False)
            reserva.detallereserva_set = form2.save()
            reserva.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class EditarReserva(UpdateView):
    model = Reserva
    form_class = ReservaForm
    context_object_name = 'reserva'
    template_name = 'reserva/editar_reserva.html'
    success_url = reverse_lazy('reserva:listar_reserva')

class EliminarReserva(DeleteView):
    model = Reserva
    template_name = 'reserva/eliminar_reserva.html'
    success_url = reverse_lazy('reserva:listar_reserva')

class DetalleReserva(DetailView):
    model = Reserva
    context_object_name = 'reserva'
    template_name = 'reserva/detalle_reserva.html'

class BuscarArea(ListView):
    model = AreaComun
    template_name = 'reserva/registrar_reserva.html'
    context_object_name = 'area'

class BusquedaAjax(TemplateView):
    def get(self, request, *args, **kwargs):
        buscarPor = request.GET['id']
        buscar = request.GET['buscar']
        if buscarPor == "sector":
            areaComun = AreaComun.objects.filter(sector__icontains=buscar)
        if buscarPor == "area_comun":
            areaComun = AreaComun.objects.filter(nombre__icontains=buscar)
        if buscarPor == "estado":
            areaComun = AreaComun.objects.filter(estado__icontains=buscar)

        data = serializers.serialize('json', areaComun,
                fields=('pk', 'nombre', 'sector', 'tmp_maximo', 'estado'))
        return HttpResponse(data, content_type='application/json')

templates/reserva/listar_reserva.html
{% extends 'base/base.html' %}

{% block title %}
    LISTA DE RESERVAS
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="../../static/css/formularios-style.css">
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1 class="text-center">Lista de Reservas</h1>
        <a href="{% url 'reserva:registrar_reserva' %}" class="btn btn-dark btn-lg mb-2">Nueva Reserva</a>

        <div class="container">
            <div class="form-group row">
                <select name="" id="" class="form-control col-12 col-sm-3 col-md-2 p-0 mr-sm-1 mb-1">
                    <option value="ci">CI</option>
                    <option value="nombre">Nombre</option>
                    <option value="app">Apl. Paterno</option>
                    <option value="apm">Apl. Materno</option>
                    <option value="nro_casa">Nro. Casa</option>
                </select>

                <input class="form-control col-12 col-sm-6 col-md-4 mr-sm-1" id="buscar" type="Buscar" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" onclick="inicio()">Buscar</button>
    {#                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
            </div>
        </div>

        <div class="row">
            <div class="table-responsive col-12">
                <table class="table table-striped table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr class="text-center">
                            <th nowrap="true" scope="col">Nro.</th>
                            <th nowrap="true" scope="col">Propietario</th>
                            <th nowrap="true" scope="col">Fecha</th>
                            <th nowrap="true" scope="col">Hora</th>
                            <th nowrap="true" scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if reserva %}
                        {% for reserva in reserva %}
                            <tr>
                                <th scope="row" class="text-center">{{ reserva.id }}</th>
                                <td>{{ reserva.id_propietario.nombre }} {{ reserva.id_propietario.app }}</td>
                                <td class="text-center">{{ reserva.fecha }}</td>
                                <td class="text-center">{{ reserva.hora }}</td>
                                <td nowrap="true" class="text-center">
{#                                    <a href="{% url 'visitante:detalle_visitante' visitante.id %}" class="btn btn-info">Detalle</a>#}
{#                                    <a href="{% url 'visitante:editar_visitante' visitante.id %}" class="btn btn-warning">Editar</a>#}
{#                                    <a href="{% url 'visitante:eliminar_visitante' visitante.id %}" class="btn btn-danger"> Eliminar</a>#}
                                </td>
                            </tr>
                    {% endfor %}
                    {% else %}
                        <h2>No hay Reservas Registradas!</h2>
                    {% endif %}
                    </tbody>
                </table>
            </div>

            <div class="d-flex flex-wrap justify-content-center">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"
                           class="btn btn-dark btn-lg mr-1">Anterior</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}"
                           class="btn btn-success btn-lg ml-1">Siguiente</a>
                    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/reserva/registrar_reserva.html
{% extends 'base/base.html' %}
{% block title %}
    REGISTRO DE RESERVA
{% endblock %}

{% block style %}
    {% load staticfiles %}
{#    <link rel="stylesheet" href="../../static/css/formularios-style.css">#}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-10 col-lg-9 col-xl-8"> {# col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6 #}
                <fieldset>
                    <legend>Nuevo</legend>
                        <h2 class="mb-4">Registro de Reserva</h2>
                        <form novalidate method="post" name="formulario_reserva" onsubmit="return validar();">
                            {% csrf_token %}

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Propietario</strong></label>
                                <input class="form-control col-11 col-md-7"
                                       id="visitante"
                                       type="text" readonly disabled
                                       placeholder="------------------">
                                <input type="hidden" name="id_propietario" value="" id="pk-visitante">
                                <a href="#" class="form-control btn btn-dark col-1 icon-search d-flex justify-content-center align-items-center"
                                   data-toggle="modal" data-target="#modalPropietario" style="font-size: 30px"></a>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Fecha</strong></label>
{#                                {{ form.fecha }}#}
                                <input type="date" name="fecha" class="form-control col-12 col-md-8" id="id_fecha">
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

{#                            <div class="form-group row">#}
{#                                <label class="col-sm-12 col-md-4 col-form-label pl-0"#}
{#                                       for=""><strong><span class="text-danger">*</span> Hora</strong></label>#}
{#                                {{ form.hora }}#}
{#                                       data-toggle="tooltip" data-placement="right"#}
{#                                <input type="time" class="form-control col-3 col-sm-3 col-md-3" name="hora" placeholder="03:00">#}
{#                            </div>#}
{##}
{#                            <div class="form-group row">#}
{#                                <label class="col-12 col-sm-4 col-form-label pl-0"#}
{#                                       for=""><strong><span class="text-danger">*</span> Hrs. de Estadia</strong></label>#}
{##}
{#                                {{ form.tmp_estadia }}#}
{#                                <input type="time" class="form-control col-3 col-sm-3 col-md-3" name="tmp_uso" placeholder="03:00">#}
{#                            </div>#}

                            <a href="#" class="btn btn-primary"
                                   data-toggle="modal" data-target="#modalAreaComun">Agregar Area</a>

                            <div class="row mt-1">
                                <div class="table-responsive col-12">
                                    <table id="tablaArea" class="table table-striped table-bordered table-hover">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th nowrap="true" scope="col">Area Social</th>
                                                <th nowrap="true" scope="col">Sector</th>
                                                <th nowrap="true" scope="col">Horas Disponible</th>
                                                <th nowrap="true" scope="col">Hora</th>
                                                <th nowrap="true" scope="col">Tiempo Uso</th>
                                                <th nowrap="true" scope="col">Accion</th>
                                            </tr>
                                        </thead>
                                        <tbody id="listAreas">

                                        </tbody>
                                    </table>
                                </div>
                            </div>

{#                            <div class="col-6 d-none invisible" id="select_select">#}
{#                            </div>#}

                            {#                                <select class="custom-select d-none hidden invisible" id="id_area_social" multiple="multiple" name="area_social">#}
{#                                </select>#}

                            <div class="row d-flex justify-content-end">
                                <button class="btn btn-success btn-lg mr-2" onclick="">Registrar</button>
                                <button onclick="window.history.back();" class="btn btn-danger btn-lg" type="button">Cancelar</button>
                            </div>

                            </form>
                        </form>
                </fieldset>
            </div>
        </div>
    </div>

    <!-- Modal -->
<div class="modal fade" id="modalPropietario" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Lista de Propietarios</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
{#          <form class="">#}
              <div class="form-group row container">
                  <select name="" id="selectPropietario" class="form-control col-4 p-0 mr-sm-1">
                      <option value="ci">CI</option>
                      <option value="nombre">Nombre</option>
                      <option value="app">Apl. Paterno</option>
                      <option value="apm">Apl. Materno</option>
                  </select>

                  <input class="form-control col-6 mr-sm-1" id="buscar" type="Buscar" placeholder="Buscar" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" onclick="inicio()">Buscar</button>
{#                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
              </div>
{#          </form>#}
          <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                  <thead class="thead-dark">
                      <tr>
                          <th>#</th>
                          <th nowrap="true" class="text-center">Nombre</th>
                          <th nowrap="true" class="text-center">Ci</th>
                          <th nowrap="true" class="text-center">Nro. Casa</th>
                          <th nowrap="true" class="text-center">Elegir</th>
                      </tr>
                  </thead>
                  <tbody id="datos">

                  </tbody>
              </table>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


        <!-- Modal Area Comun-->
<div class="modal fade" id="modalAreaComun" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Lista de Areas Comunes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
{#          <form class="">#}
              <div class="form-group row container">
                  <select name="" id="selectArea" class="form-control col-4 p-0 mr-sm-1">
                      <option value="sector">Sector</option>
                      <option value="area_comun">Area Comun</option>
                      <option value="estado">Estado</option>
                  </select>

                  <input class="form-control col-6 mr-sm-1" id="buscarArea" type="Buscar" placeholder="Buscar" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" onclick="BuscarArea()">Buscar</button>
{#                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
              </div>
{#          </form>#}
          <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                  <thead class="thead-dark">
                      <tr>
                          <th>#</th>
                          <th nowrap="true" class="text-center">Area Social</th>
                          <th nowrap="true" class="text-center">Sector</th>
                          <th nowrap="true" class="text-center">Maximo Permitido</th>
                          <th nowrap="true" class="text-center">Elegir</th>
                      </tr>
                  </thead>
                  <tbody id="datosModal">

                  </tbody>
              </table>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block extasjs %}
    <script src="{% static 'js/validar-reserva.js' %}"></script>
    <script src="{% static 'js/modal-propietario.js' %}"></script>
    <script src="{% static 'js/modal-areaComun.js' %}"></script>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}