Administracion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('propietario/', include('Apps.Propietario.urls')),
    path('visitante/', include('Apps.Visitante.urls')),
    path('areacomun/', include('Apps.AreaComun.urls')),
    path('reserva/', include('Apps.Reserva.urls')),
    path('usuario/', include('Apps.usuario.urls')),
    path('', LoginView.as_view(template_name='home/index.html'), name='home'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('accounts/login/', LoginView.as_view(template_name='usuario/login.html'), name='login'),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/Visitante/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from Apps.Visitante.views import RegistrarVisitante, ListarVisitante,\
    EditarVisitante, EliminarVisitante, DetalleVisitante

app_name = 'visitante'

urlpatterns = [
    path('listar/', login_required(ListarVisitante.as_view()), name="listar_visitante"),
    path('detalle/<pk>/', login_required(DetalleVisitante.as_view()), name="detalle_visitante"),
    path('registrar/', login_required(RegistrarVisitante.as_view()), name="registrar_visitante"),
    path('editar/<pk>/', login_required(EditarVisitante.as_view()), name="editar_visitante"),
    path('eliminar/<pk>/', login_required(EliminarVisitante.as_view()), name="eliminar_visitante"),
]

Apps/Visitante/models.py
from django.db import models

# Create your models here.
from Apps.Propietario.models import Propietario

AUTOMOVIL = 'AUTO'
CAMINANDO = 'PIE'
BICICLETA = 'BICI'

INGRESO = (
    (AUTOMOVIL, 'Automovil'),
    (CAMINANDO, 'Caminando'),
    (BICICLETA, 'Bicicleta')
)

class Visitante(models.Model):
    ci = models.CharField(max_length=12, null=False)
    nombre = models.CharField(max_length=30, null=False)
    app = models.CharField(max_length=30, null=False)
    apm = models.CharField(max_length=30, null=False)
    tmp_estadia = models.TimeField()
    mod_ing = models.CharField(max_length=10, choices=INGRESO)
    id_propietario = models.ForeignKey(Propietario, null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)  # Optiene la fecha de registro automaticamente
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0} {1}'.format(self.nombre, self.app)

Apps/Visitante/forms.py
from django import forms
from Apps.Visitante.models import Visitante

class VisitanteForm(forms.ModelForm):
    class Meta:
        model = Visitante
        fields = '__all__'
        labels = {
            'ci': 'CI.',
            'nombre': 'Nombres',
            'app': 'Apellido P.',
            'apm': 'Apellido M.',
            'tmp_estadia': 'Timepo Estadia',
            'mod_ing': 'Entro /en',
            'id_propietario': 'Visita A'
        }

        widgets = {
            'ci': forms.NumberInput(attrs={'class':'form-control col-5 col-sm-5 col-md-5', 'id':'ci'}),
            'nombre': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'nombre'}),
            'app': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'app'}),
            'apm': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'apm'}),
            'django.conf.locale.id': forms.TextInput(attrs={'class': 'form-control col-12 col-md-8', 'id': 'id_propietario'}),
            'tmp_estadia': forms.TimeInput(attrs={'class':'form-control col-5 col-sm-5 col-md-5', 'id':'tmp_estadia'}),
            'mod_ing': forms.Select(attrs={'class': 'form-control col-12 col-md-8', 'id': 'mod_ing'}),
        }

Apps/Visitante/views.py
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Visitante
from Apps.Visitante.forms import VisitanteForm


class ListarVisitante(ListView):
    model = Visitante
    template_name = 'visitante/listar_visita.html'
    context_object_name = 'visitante'
    paginate_by = 10

class RegistrarVisitante(CreateView):
    model = Visitante
    # fields = '__all__'
    form_class = VisitanteForm
    template_name = 'visitante/registrar_visita.html'
    success_url = reverse_lazy('visitante:listar_visitante')

class EditarVisitante(UpdateView):
    model = Visitante
    form_class = VisitanteForm
    context_object_name = 'visitante'
    template_name = 'visitante/editar_visita.html'
    success_url = reverse_lazy('visitante:listar_visitante')

class EliminarVisitante(DeleteView):
    model = Visitante
    template_name = 'visitante/eliminar_visita.html'
    success_url = reverse_lazy('visitante:listar_visitante')

class DetalleVisitante(DetailView):
    model = Visitante
    context_object_name = 'visitante'
    template_name = 'visitante/detalle_visita.html'

templates/visitante/detalle_visita.html
{% extends 'base/base.html' %}
{% block title %}
    DETALLE DE VISITA
{% endblock %}

{% block style %}
    {% load staticfiles %}
{#    <link rel="stylesheet" href="../../static/css/formularios-style.css">#}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/validar-visita.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Informacion</legend>
                        <h2 class="mb-4">Detalle de Visita</h2>
                        <form>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>CI :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.ci }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Nombres :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.nombre }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Apellidos :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.app }}  {{ visitante.apm }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Visito a :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.id_propietario.nombre }}
                                    {{ visitante.id_propietario.app }} {{ visitante.id_propietario.apm }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>


                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Ingreso en/a :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.mod_ing.title }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Fecha Ingreso :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.created_at }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="row d-flex justify-content-end">
                                <button onclick="window.history.back();" class="btn btn-danger btn-lg" type="button">Cancelar</button>
                            </div>
                        </form>
                </fieldset>
            </div>
        </div>
    </div>

{% endblock %}

{% block extasjs %}
    <script src="{% static 'js/modal-propietario.js' %}"></script>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

templates/visitante/editar_visita.html
{% extends 'base/base.html' %}
{% block title %}
    EDITAR VISITA
{% endblock %}

{% block style %}
    {% load staticfiles %}
{#    <link rel="stylesheet" href="../../static/css/formularios-style.css">#}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/validar-visita.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Editar</legend>
                        <h2 class="mb-4">Edicion de Visita</h2>
                        <form novalidate method="post" name="formulario_visita" onsubmit="return validar();">
                            {% csrf_token %}

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> CI.</strong></label>
                                {{ form.ci }}
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Nombres</strong></label>
                                {{ form.nombre }}
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Apl. Paterno</strong></label>
                                {{ form.app }}
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Apl. Materno</strong></label>
                                {{ form.apm }}
                            </div>

                            <h1></h1>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Visita A:</strong></label>
                                <input class="form-control col-11 col-md-7"
                                       id="visitante"
                                       type="text" readonly disabled
                                       placeholder="Visita A" value="{{ visitante.id_propietario }}">
                                <input type="hidden" name="id_propietario" value="{{ visitante.id_propietario.id }}" id="pk-visitante">
                                <a href="#" class="form-control btn btn-dark col-1 icon-search d-flex justify-content-center align-items-center"
                                   data-toggle="modal" data-target="#myModal" style="font-size: 30px"></a>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-4 col-form-label pl-0"
                                       for=""><strong>* Hrs. de Estadia</strong></label>

                                {{ form.tmp_estadia }}
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Entro en/a</strong></label>

                                {% if visitante.mod_ing == "AUTO" %}
                                    <div class="form-group contenedor-radio">
                                        <input class="" id="auto"
                                               type="radio" name="mod_ing" value="AUTO" checked>
                                        <label class="label-radio"
                                               for="auto">Automovil</label>

                                        <input class="" id="pie"
                                               type="radio" name="mod_ing" value="PIE">
                                        <label class="label-radio"
                                               for="pie">Pie</label>

                                        <input class="" id="bici"
                                               type="radio" name="mod_ing" value="BICI">
                                        <label class="label-radio"
                                               for="bici">Bicicleta</label>
                                    </div>
                                {% endif %}

                                {% if visitante.mod_ing == "PIE" %}
                                    <div class="form-group contenedor-radio">
                                        <input class="" id="auto"
                                               type="radio" name="mod_ing" value="AUTO">
                                        <label class="label-radio"
                                               for="auto">Automovil</label>

                                        <input class="" id="pie"
                                               type="radio" name="mod_ing" value="PIE" checked>
                                        <label class="label-radio"
                                               for="pie">Pie</label>

                                        <input class="" id="bici"
                                               type="radio" name="mod_ing" value="BICI">
                                        <label class="label-radio"
                                               for="bici">Bicicleta</label>
                                    </div>
                                {% endif %}

                                {% if visitante.mod_ing == "BICI" %}
                                    <div class="form-group contenedor-radio">
                                        <input class="" id="auto"
                                               type="radio" name="mod_ing" value="AUTO">
                                        <label class="label-radio"
                                               for="auto">Automovil</label>

                                        <input class="" id="pie"
                                               type="radio" name="mod_ing" value="PIE">
                                        <label class="label-radio"
                                               for="pie">Pie</label>

                                        <input class="" id="bici"
                                               type="radio" name="mod_ing" value="BICI" checked>
                                        <label class="label-radio"
                                               for="bici">Bicicleta</label>
                                    </div>
                                {% endif %}

                            </div>
{##}
{##}
{#                            SE OCULTO ESTA PARTE#}
{#                            <div class="form-group row d-none">#}
{#                                <label class="col-sm-12 col-md-7 col-lg-7 col-form-label"#}
{#                                       for="">Tiempo de Estadia</label>#}
{#                                <input class="form-control col-sm-12 col-md-5 col-lg-5"#}
{#                                       type="time"#}
{#                                       data-toggle="tooltip" data-placement="top" data-html="true"#}
{#                                       title="Tiempo que estuvo en el <b>Establecimiento</b>">#}
{#                            </div>#}
{#                            <div class="form-group row d-none">#}
{#                                <label class="col-sm-12 col-md-7 col-lg-7 col-form-label"#}
{#                                       for="">Fecha de Salida</label>#}
{#                                <input class="form-control col-sm-12 col-md-5 col-lg-5"#}
{#                                       type="date"#}
{#                                       placeholder="dd/mm/aaaa"#}
{#                                       data-toggle="tooltip" data-placement="top" data-html="true"#}
{#                                       title="Fecha de salida del <b>Establecimiento</b>">#}
{#                            </div>#}
                            <div class="row d-flex justify-content-end">
                                <button class="btn btn-success btn-lg mr-2" onclick="">Actualizar</button>
                                <button onclick="window.history.back();" class="btn btn-danger btn-lg" type="button">Cancelar</button>
                            </div>
                        </form>
                </fieldset>
            </div>
        </div>
    </div>

    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Lista de Propietarios</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
{#          <form class="">#}
              <div class="form-group row">
                  <select name="" id="selectPropietario" class="form-control col-4 p-0 mr-sm-1">
                      <option value="ci">CI</option>
                      <option value="nombre">Nombre</option>
                      <option value="app">Apl. Paterno</option>
                      <option value="apm">Apl. Materno</option>
                  </select>

                  <input class="form-control col-6 mr-sm-1" id="buscar" type="Buscar" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" onclick="inicio()">Buscar</button>
{#                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
              </div>
{#          </form>#}
          <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                  <thead class="thead-dark">
                      <tr>
                          <th>#</th>
                          <th nowrap="true">Nombre</th>
                          <th nowrap="true">Ci</th>
                          <th nowrap="true">Nro. Casa</th>
                          <th nowrap="true">Quien?</th>
                      </tr>
                  </thead>
                  <tbody id="datos">

                  </tbody>
              </table>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extasjs %}
    <script src="{% static 'js/validar-visita.js' %}"></script>
    <script src="{% static 'js/modal-propietario.js' %}"></script>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

templates/visitante/eliminar_visita.html
{% extends 'base/base.html' %}

{% block title %}
ELIMINAR VISITA
{% endblock %}

{% block style %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Eliminar</legend>
                    <h3>Desea eliminar esta Visita?</h3>

                        <form method="post">
                            {% csrf_token %}

                             <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>CI :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.ci }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Visitante :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.nombre }} {{ visitante.app }} {{ visitante.apm }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Visito a :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ visitante.id_propietario.nombre }}
                                    {{ visitante.id_propietario.app }} {{ visitante.id_propietario.apm }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <button class="btn btn-danger" type="submit">Si, Eliminar</button>
                            <button type="button" onclick="window.history.back();" class="btn btn-primary">Cancelar</button>

                        </form>

                </fieldset>
            </div>
        </div>
    </div>
{% endblock %}

templates/visitante/listar_visita.html
{% extends 'base/base.html' %}

{% block title %}
    LISTA DE VISITAS
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="../../static/css/formularios-style.css">
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1 class="text-center">Lista de Visitas</h1>
        <a href="{% url 'visitante:registrar_visitante' %}" class="btn btn-dark btn-lg mb-2">Nueva Visita</a>

        <div class="container">
            <div class="form-group row">
                <select name="" id="" class="form-control col-12 col-sm-3 col-md-2 p-0 mr-sm-1 mb-1">
                    <option value="ci">CI</option>
                    <option value="nombre">Nombre</option>
                    <option value="app">Apl. Paterno</option>
                    <option value="apm">Apl. Materno</option>
                    <option value="nro_casa">Nro. Casa</option>
                </select>

                <input class="form-control col-12 col-sm-6 col-md-4 mr-sm-1" id="buscar" type="Buscar" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" onclick="inicio()">Buscar</button>
    {#                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
            </div>
        </div>

        <div class="row">
            <div class="table-responsive col-12">
                <table class="table table-striped table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr class="text-center">
                            <th nowrap="true" scope="col">Nro.</th>
                            <th nowrap="true" scope="col">Nombre</th>
                            <th nowrap="true" scope="col">Visita a</th>
                            <th nowrap="true" scope="col">Fecha Ingreso</th>
                            <th nowrap="true" scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if visitante %}
                        {% for visitante in visitante %}
                            <tr>
                                <th scope="row" class="text-center">{{ visitante.id }}</th>
                                <td>{{ visitante.nombre }} {{ visitante.app }}</td>
                                <td class="text-center">{{ visitante.id_propietario }}</td>
                                <td class="text-center">{{ visitante.created_at }}</td>
                                <td nowrap="true" class="text-center">
                                    <a href="{% url 'visitante:detalle_visitante' visitante.id %}" class="btn btn-info">Detalle</a>
                                    <a href="{% url 'visitante:editar_visitante' visitante.id %}" class="btn btn-warning">Editar</a>
                                    <a href="{% url 'visitante:eliminar_visitante' visitante.id %}" class="btn btn-danger"> Eliminar</a>
                                </td>
                            </tr>
                    {% endfor %}
                    {% else %}
                        <h2>No hay Visitantes Registrados!</h2>
                    {% endif %}
                    </tbody>
                </table>
            </div>

            <div class="d-flex flex-wrap justify-content-center">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"
                           class="btn btn-dark btn-lg mr-1">Anterior</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}"
                           class="btn btn-success btn-lg ml-1">Siguiente</a>
                    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}