Administracion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('propietario/', include('Apps.Propietario.urls')),
    path('visitante/', include('Apps.Visitante.urls')),
    path('areacomun/', include('Apps.AreaComun.urls')),
    path('reserva/', include('Apps.Reserva.urls')),
    path('usuario/', include('Apps.usuario.urls')),
    path('', LoginView.as_view(template_name='home/index.html'), name='home'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('accounts/login/', LoginView.as_view(template_name='usuario/login.html'), name='login'),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/Propietario/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from Apps.Propietario.views import RegistrarPropietario, ListarPropietario,\
    BusquedaAjax, EditarPropietario, EliminarPropietario, DetallePropietario

app_name = 'propietario'

urlpatterns = [
    path('listar/', login_required(ListarPropietario.as_view()), name="listar_propietario"),
    path('detalle/<pk>/', login_required(DetallePropietario.as_view()), name="detalle_propietario"),
    path('registrar/', login_required(RegistrarPropietario.as_view()), name="registrar_propietario"),
    path('editar/<pk>/', login_required(EditarPropietario.as_view()), name="editar_propietario"),
    path('eliminar/<pk>/', login_required(EliminarPropietario.as_view()), name="eliminar_propietario"),
    path('busquedaAjax/', login_required(BusquedaAjax.as_view()), name="busqueda_ajax"),
]

Apps/Propietario/models.py
from django.db import models

# Create your models here.

class Propietario(models.Model):
    nombre = models.CharField(max_length=30)
    app = models.CharField(max_length=30)
    apm = models.CharField(max_length=30)
    ci = models.CharField(max_length=12)
    nro_casa = models.CharField(max_length=10)

    def __str__(self):
        return '{0} {1}'.format(self.nombre, self.app)

Apps/Propietario/forms.py
from django import forms
from Apps.Propietario.models import Propietario

class PropietarioForm(forms.ModelForm):
    class Meta:
        model = Propietario
        fields = '__all__'
        labels = {
            'ci': 'CI.',
            'nombre': 'Nombres',
            'app': 'Apellido P.',
            'apm': 'Apellido M.',
            'nro_casa': 'Nro. Casa'
        }

        widgets = {
            'ci': forms.NumberInput(attrs={'class':'form-control col-5 col-sm-5 col-md-5', 'id':'ci'}),
            'nombre': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'nombre':'nombre'}),
            'app': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'app':'app'}),
            'apm': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'apm':'apm'}),
            'nro_casa': forms.NumberInput(attrs={'class':'form-control col-5 col-sm-5 col-md-5', 'nro_casa':'nro_casa'}),
        }

Apps/Propietario/views.py
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from .models import Propietario
from Apps.Propietario.forms import PropietarioForm


class ListarPropietario(ListView):
    model = Propietario
    template_name = 'propietario/listar_propietario.html'
    context_object_name = 'propietario'
    paginate_by = 10

class RegistrarPropietario(CreateView):
    model = Propietario
    # fields = '__all__'
    form_class = PropietarioForm
    template_name = 'propietario/registrar_propietario.html'
    success_url = reverse_lazy('propietario:listar_propietario')

class EditarPropietario(UpdateView):
    model = Propietario
    form_class = PropietarioForm
    context_object_name = 'propietario'
    template_name = 'propietario/registrar_propietario.html'
    success_url = reverse_lazy('propietario:listar_propietario')

class EliminarPropietario(DeleteView):
    model = Propietario
    template_name = 'propietario/eliminar_propietario.html'
    success_url = reverse_lazy('propietario:listar_propietario')

class DetallePropietario(DetailView):
    model = Propietario
    context_object_name = 'propietario'
    template_name = 'propietario/detalle_propietario.html'



class BuscarPropietario(ListView):
    model = Propietario
    template_name = 'visitante/registrar_visita.html'
    context_object_name = 'propietario'

class BusquedaAjax(TemplateView):
    def get(self, request, *args, **kwargs):
        buscarPor = request.GET['id']
        buscar = request.GET['buscar']
        if buscarPor == "ci":
            propietario = Propietario.objects.filter(ci__contains=buscar)
        if buscarPor == "nombre":
            propietario = Propietario.objects.filter(nombre__contains=buscar)
        if buscarPor == "app":
            propietario = Propietario.objects.filter(app__contains=buscar)
        if buscarPor == "apm":
            propietario = Propietario.objects.filter(apm__contains=buscar)

        data = serializers.serialize('json', propietario,
                fields=('nombre', 'app', 'apm', 'ci', 'nro_casa'))
        return HttpResponse(data, content_type='application/json')

templates/propietario/busqueda_propietario.html
{% extends 'base/base.html' %}

templates/propietario/detalle_propietario.html
{% extends 'base/base.html' %}
{% block title %}
DETALLE DE PROPIETARIO
{% endblock %}

{% block style %}
    {% load staticfiles %}
{#    <link rel="stylesheet" href="../../static/css/formularios-style.css">#}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/validar-visita.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Informacion</legend>
                        <h2 class="mb-4">Detalle de Propietario</h2>
                        <form>
                            <div class="row d-flex justify-content-center">
                                <img class="img-fluid img-thumbnail w-25 h-25 rounded-circle" src="{% static 'img/usuario.png' %}" alt="No se pudo Cargar">
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>CI :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ propietario.ci }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Nombres :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ propietario.nombre }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Apellidos :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ propietario.app }}  {{ visitante.apm }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Nro. Casa :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ propietario.nro_casa }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="row d-flex justify-content-end">
                                <button onclick="window.history.back();" class="btn btn-danger btn-lg" type="button">Cancelar</button>
                            </div>
                        </form>
                </fieldset>
            </div>
        </div>
    </div>

{% endblock %}

{% block extasjs %}
    <script src="{% static 'js/modal-propietario.js' %}"></script>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

templates/propietario/eliminar_propietario.html
{% extends 'base/base.html' %}

{% block title %}
ELIMINAR PROPIETARIO
{% endblock %}

{% block style %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Eliminar</legend>
                        <h3 class="mb-4">Desea eliminar este Propietario?</h3>

                        <form method="post">
                            {% csrf_token %}

                            <div class="row d-flex justify-content-center">
                                <img class="img-fluid img-thumbnail w-25 h-25 rounded-circle" src="{% static 'img/usuario.png' %}" alt="No se pudo Cargar">
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>CI :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ propietario.ci }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Propietario :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ propietario.nombre }} {{ propietario.app }} {{ propietario.apm }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Nro Casa :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ propietario.nro_casa }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <button class="btn btn-danger" type="submit">Si, Eliminar</button>
                            <button type="button" onclick="window.history.back();" class="btn btn-primary">Cancelar</button>

                        </form>

                </fieldset>
            </div>
        </div>
    </div>
{% endblock %}

templates/propietario/listar_propietario.html
{% extends 'base/base.html' %}

{% block title %}
LISTA DE PROPIETARIO
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1 class="text-center">Lista de Propietarios</h1>
        <a href="{% url 'propietario:registrar_propietario' %}" class="btn btn-dark btn-lg mb-2">Nuevo Propietario</a>

    <div class="container">
        <div class="form-group row">
            <select name="" id="" class="form-control col-12 col-sm-3 col-md-2 p-0 mr-sm-1 mb-1">
                <option value="ci">CI</option>
                <option value="nombre">Nombre</option>
                <option value="app">Apl. Paterno</option>
                <option value="apm">Apl. Materno</option>
            </select>

            <input class="form-control col-12 col-sm-6 col-md-4 mr-sm-1" id="buscar" type="Buscar" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" onclick="inicio()">Buscar</button>
{#                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
        </div>
    </div>

        <div class="row">
            <div class="table-responsive col-12">
                <table class="table table-striped table-bordered table-hover">
                    <thead class="thead-dark">
                    <tr>
                        <th nowrap="true" scope="col">#</th>
                        <th nowrap="true" scope="col">Propietario</th>
                        <th nowrap="true" scope="col" class="text-center">Ci</th>
                        <th nowrap="true" scope="col" class="text-center">Numero de Casa</th>
                        <th nowrap="true" scope="col" class="text-center">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if propietario %}
                        {% for propietario in propietario %}
                            <tr>
                                <th scope="row">{{ propietario.id }}</th>
                                <td>{{ propietario.nombre }}</td>
                                <td class="text-center">{{ propietario.ci }}</td>
                                <td class="text-center">{{ propietario.nro_casa }}</td>
                                <td nowrap="true" class="text-center">
                                    <a href="{% url 'propietario:detalle_propietario' propietario.id %}" class="btn btn-info">Detalle</a>
                                    <a href="{% url 'propietario:editar_propietario' propietario.id %}" class="btn btn-warning">Editar</a>
                                    <a href="{% url 'propietario:eliminar_propietario' propietario.id %}" class="btn btn-danger"> Eliminar</a>
                                </td>
                            </tr>
                    {% endfor %}
                    {% else %}
                        <h2>No hay Propietarios Registrados!</h2>
                    {% endif %}
                    </tbody>
                </table>

                <div class="d-flex flex-wrap justify-content-center">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"
                           class="btn btn-dark btn-lg mr-1">Anterior</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}"
                           class="btn btn-success btn-lg ml-1">Siguiente</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/propietario/registrar_propietario.html
{% extends 'base/base.html' %}

{% block title %}
    {% if propietario %}
        EDITAR PROPIETARIO
        {% else %}
        NUEVO PROPIETARIO
    {% endif %}
{% endblock %}

{% block style %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>
                        {% if object %}
                            Editar
                        {% else %}
                            Nuevo
                        {% endif %}
                    </legend>
                        <h2 class="mb-4">
                            {% if object %}
                            Edicion de Propietario
                        {% else %}
                            Registro de Propietario
                        {% endif %}
                        </h2>
                        <form novalidate method="post" enctype="multipart/form-data" name="formulario_propietario" onsubmit="return validar();">
                            {% csrf_token %}
                    {#        {{ form.as_p }}#}

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="ci"><strong><span class="text-danger">*</span> CI.</strong></label>
                                {{ form.ci }}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="nombre"><strong><span class="text-danger">*</span> Nombre.</strong></label>
                                {{ form.nombre }}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="app"><strong><span class="text-danger">*</span> Apellido P.</strong></label>
                                {{ form.app }}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*</span> Apellido M.</strong></label>
                                {{ form.apm }}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="nro_casa"><strong><span class="text-danger">*</span> Nro. Casa.</strong></label>
                                {{ form.nro_casa }}
                            </div>

                            <div class="row d-flex justify-content-end">
                                <button class="btn btn-success btn-lg mr-2" onclick="">
                                    {% if object %}
                                        Actualizar
                                    {% else %}
                                        Registrar
                                    {% endif %}
                                </button>
                                <button class="btn btn-danger btn-lg" type="button" onclick='window.history.back();'>Cancelar</button>
                            </div>
                        </form>
                </fieldset>
            </div>
        </div>
    </div>
{% endblock %}

{% block extasjs %}
<script src="{% static 'js/validar-propietario.js' %}"></script>
{% endblock %}