Administracion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('propietario/', include('Apps.Propietario.urls')),
    path('visitante/', include('Apps.Visitante.urls')),
    path('areacomun/', include('Apps.AreaComun.urls')),
    path('reserva/', include('Apps.Reserva.urls')),
    path('usuario/', include('Apps.usuario.urls')),
    path('', LoginView.as_view(template_name='home/index.html'), name='home'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('accounts/login/', LoginView.as_view(template_name='usuario/login.html'), name='login'),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/AreaComun/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from Apps.AreaComun.views import RegistrarAreaComun, ListarAreaComun,\
    EditarAreaComun, EliminarAreaComun, DetalleAreaComun

app_name = 'areaComun'

urlpatterns = [
    path('listar/', login_required(ListarAreaComun.as_view()), name="listar_areaComun"),
    path('detalle/<pk>/', login_required(DetalleAreaComun.as_view()), name="detalle_areaComun"),
    path('registrar/', login_required(RegistrarAreaComun.as_view()), name="registrar_areaComun"),
    path('editar/<pk>/', login_required(EditarAreaComun.as_view()), name="editar_areaComun"),
    path('eliminar/<pk>/', login_required(EliminarAreaComun.as_view()), name="eliminar_areaComun"),
]

Apps/AreaComun/models.py
from django.db import models

# Create your models here.

CANCHAS = 'CAN'
PISCINAS = 'PIS'
CHURRASQUERAS = 'CHU'
GYM = 'GYM'

AREAS = (
    (CANCHAS, 'Cancha'),
    (PISCINAS, 'Piscina'),
    (CHURRASQUERAS, 'Churrasquera'),
    (GYM, 'Gym')
)


HABILITADO = 'H'
DESHABILITADO = 'D'
MANTENIMIENTO = 'M'

ESTADO = (
    (HABILITADO, 'Habilitado'),
    (DESHABILITADO, 'Deshabilitado'),
    (MANTENIMIENTO, 'Mantenimiento')
)

class AreaComun(models.Model):
    categoria = models.CharField(max_length=3, choices=AREAS)
    nombre = models.CharField(max_length=30, null=False)
    sector = models.CharField(max_length=30, null=False)
    imagen = models.FileField(null=False, upload_to='area_comun')
    descripcion = models.TextField(null=True, blank=True)
    disp_desde = models.TimeField()
    dip_hasta = models.TimeField()
    tmp_maximo = models.TimeField()
    estado = models.CharField(max_length=1, choices=ESTADO)
    created_at = models.DateTimeField(auto_now_add=True)  # Optiene la fecha de registro automaticamente
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0}'.format(self.nombre)

Apps/AreaComun/forms.py
from django import forms
from Apps.AreaComun.models import AreaComun

class AreaComunForm(forms.ModelForm):
    class Meta:
        model = AreaComun
        fields = '__all__'
        labels = {
            'categoria': 'Categoria',
            'nombre': 'Nombre del Area',
            'sector': 'Sector',
            'imagen': 'Imagen',
            'descripcion': 'Descipcion',
            'disp_desde': 'Disponible desde',
            'dip_hasta': 'Disponible hasta',
            'tmp_maximo': 'Tiempo Maximo de Uso',
            'estado': 'Estado'
        }

        widgets = {
            'categoria': forms.Select(attrs={'class': 'custom-select col-12 col-md-8', 'id': 'categoria'}),
            'nombre': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'nombre'}),
            'sector': forms.TextInput(attrs={'class':'form-control col-12 col-md-8', 'id':'sector'}),
            'imagen': forms.FileInput(attrs={'class':'form-control col-5 col-sm-5 col-md-5', 'id':'imagen'}),
            'descripcion': forms.Textarea(attrs={'class':'form-control col-12 col-md-8', 'id':'descripcion', 'rows':"3"}),
            'disp_desde': forms.TimeInput(attrs={'class':'form-control col-5 col-sm-5 col-md-5', 'id':'dis_desde'}),
            'dip_hasta': forms.TimeInput(attrs={'class':'form-control col-5 col-sm-5 col-md-5', 'id':'dis_hasta'}),
            'tmp_maximo': forms.TimeInput(attrs={'class': 'form-control col-5 col-sm-5 col-md-5', 'id': 'tmp_maximo'}),
            'estado': forms.Select(attrs={'class': 'form-control col-12 col-md-8', 'id': 'estado'}),
        }

Apps/AreaComun/views.py
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from .models import AreaComun
from Apps.AreaComun.forms import AreaComunForm


class ListarAreaComun(ListView):
    model = AreaComun
    template_name = 'areaComun/listar_areaComun.html'
    context_object_name = 'areaComun'
    paginate_by = 10

class RegistrarAreaComun(CreateView):
    model = AreaComun
    # fields = '__all__'
    form_class = AreaComunForm
    template_name = 'areaComun/registrar_areaComun.html'
    success_url = reverse_lazy('areaComun:listar_areaComun')

class EditarAreaComun(UpdateView):
    model = AreaComun
    form_class = AreaComunForm
    context_object_name = 'areaComun'
    template_name = 'areaComun/editar_areaComun.html'
    success_url = reverse_lazy('areaComun:listar_areaComun')

class EliminarAreaComun(DeleteView):
    model = AreaComun
    template_name = 'areaComun/eliminar_areaComun.html'
    success_url = reverse_lazy('areaComun:listar_areaComun')

class DetalleAreaComun(DetailView):
    model = AreaComun
    context_object_name = 'areaComun'
    template_name = 'areaComun/detalle_areaComun.html'

templates/areaComun/detalle_areaComun.html
{% extends 'base/base.html' %}
{% block title %}
    DETALLE DE AREA COMUN
{% endblock %}

{% block style %}
    {% load staticfiles %}
{#    <link rel="stylesheet" href="../../static/css/formularios-style.css">#}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/validar-visita.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Informacion</legend>
                        <h2 class="mb-4">Detalle de Area Comun</h2>
                        <form novalidate method="post" enctype="multipart/form-data" name="formulario_visita" onsubmit="return validar();">
                            {% csrf_token %}

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Categoria</strong>
                                </label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areaComun.get_categoria_display }}</p>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Nombre</strong>
                                </label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areaComun.nombre }}</p>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="">
                                    <strong>Sector
                                    </strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areaComun.sector }}</p>
                            </div>

                            <br>
                            <br>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*
                                </span> Imagen</strong></label>

                                <div class="col-md-4" id="imagePreview">
                                    {% if areaComun.imagen %}
                                        <img src="{% static 'Imagenes/' %}{{ areaComun.imagen }}" alt="">
                                    {% else %}
                                        <img src="" alt="">
                                    {% endif %}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong> Descripcion</strong>
                                </label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areaComun.descripcion }}</p>
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-4 col-form-label pl-0"
                                       for=""><strong>Disponible Desde</strong>
                                </label>
                                <p class="col-sm-3 col-form-label pl-0">{{ areaComun.disp_desde }}</p>
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-4 col-form-label pl-0"
                                       for=""><strong>Disponible Hasta</strong>
                                </label>
                                <p class="col-sm-3 col-form-label pl-0">{{ areaComun.dip_hasta }}</p>
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-4 col-form-label pl-0"
                                       for=""><strong>Tiempo Maximo</strong>
                                </label>
                                <p class="col-3 col-form-label pl-0">{{ areaComun.tmp_maximo }}</p>
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-4 col-form-label pl-0"
                                       for=""><strong>Estado</strong>
                                </label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areaComun.get_estado_display }}</p>
                            </div>

                            <div class="row d-flex justify-content-end">
                                <button class="btn btn-success btn-lg mr-2" onclick="">Actualizar</button>
                                <button onclick="window.history.back();" class="btn btn-danger btn-lg" type="button">Cancelar</button>
                            </div>
                        </form>
                </fieldset>
            </div>
        </div>
    </div>

{% endblock %}

{% block extasjs %}
    <script src="{% static 'js/modal-propietario.js' %}"></script>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}
{##}
{#{% if areaComun.disp_desde.hour <= 9 %}#}
{#    value="0{{ areaComun.disp_desde.hour }}#}
{#    {% if areaComun.disp_desde.minute <= 9 %}#}
{#        :0{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% else %}#}
{#        :{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% endif %}#}
{#{% else %}#}
{#    value="{{ areaComun.disp_desde.hour }}:0{{ areaComun.dip_hasta.minute }}"> A:#}
{#    {% if areaComun.disp_desde.minute <= 9 %}#}
{#        :0{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% else %}#}
{#        :{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% endif %}#}
{#{% endif %}#}

templates/areaComun/editar_areaComun.html
{% extends 'base/base.html' %}
{% block title %}
    EDITAR AREA COMUN
{% endblock %}

{% block style %}
    {% load staticfiles %}
{#    <link rel="stylesheet" href="../../static/css/formularios-style.css">#}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/validar-visita.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Editar</legend>
                        <h2 class="mb-4">Edicion de Area Comun</h2>
                        <form novalidate method="post" enctype="multipart/form-data" name="formulario_visita" onsubmit="return validar();">
                            {% csrf_token %}

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="">
                                    <strong>
                                        <span class="text-danger">*</span> Categoria
                                    </strong></label>
                                {{ form.categoria }}
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="">
                                    <strong><span class="text-danger">*</span> Nombre
                                    </strong></label>
                                {{ form.nombre }}
                                <div class="invalid-feedback">
                                  Please choose a username.
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for="">
                                    <strong><span class="text-danger">*</span> Sector
                                    </strong></label>
                                {{ form.sector }}
                            </div>

                            <br>
                            <br>
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong><span class="text-danger">*
                                </span> Imagen</strong></label>
{#                                {{ form.imagen }}#}
                                <div class="custom-file col-md-4">
                                    <input onchange="mostrarImagen();" type="file" name="imagen" class="d-none" id="imagen"> {# //idcustomFileLang #}
                                    <label class="btn btn-dark" for="imagen">Subir Imagen</label>
                                </div>

                                <div class="col-md-4" id="imagePreview">
                                    {% if areaComun.imagen %}
                                        <img src="{% static 'Imagenes/' %}{{ areaComun.imagen }}" alt="">
                                    {% else %}
                                        <img src="" alt="">
                                    {% endif %}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong> Descripcion</strong>
                                </label>
                                {{ form.descripcion }}
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-5 col-form-label pl-0"
                                       for="">
                                    <strong><span class="text-danger">*</span> Disponible Desde
                                    </strong>
                                </label>
{#                                {{ form.disp_desde }}#}

{#                                {{ form.disp_desde }}#}
{#                                {{ form.dip_hasta }}#}

                                <input type="time" class="form-control col-3 mr-1"
                                       name="disp_desde" placeholder="03:30" {% if areaComun.disp_desde.hour <= 9 %}value="0{{ areaComun.disp_desde.hour }}{% if areaComun.disp_desde.minute <= 9 %}:0{{ areaComun.disp_desde.minute }}:00"> A:{% else %}:{{ areaComun.disp_desde.minute }}:00"> A:{% endif %}{% else %}value="{{ areaComun.disp_desde.hour }}:0{{ areaComun.disp_desde.minute }}:00"> A:{% if areaComun.disp_desde.minute <= 9 %}:0{{ areaComun.disp_desde.minute }}:00"> A:{% else %}:{{ areaComun.disp_desde.minute }}:00"> A:{% endif %}
                                       {% endif %}

                                <input type="time" class="form-control col-3 ml-1"
                                       name="dip_hasta" placeholder="03:30" {% if areaComun.dip_hasta.hour <= 9 %}value="0{{ areaComun.dip_hasta.hour }}{% if areaComun.dip_hasta.minute <= 9 %}:0{{ areaComun.dip_hasta.minute }}:00">{% else %}:{{ areaComun.dip_hasta.minute }}:00">{% endif %}{% else %}value="{{ areaComun.dip_hasta.hour }}{% if areaComun.dip_hasta.minute <= 9 %}:0{{ areaComun.dip_hasta.minute }}:00">{% else %}:{{ areaComun.dip_hasta.minute }}:00">{% endif %}
                                       {% endif %}
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-5 col-form-label pl-0"
                                       for="">
                                    <strong><span class="text-danger">*</span> Tiempo Maximo
                                    </strong>
                                </label>
{#                                {{ form.disp_desde }}#}
{#                                {{ form.tmp_maximo }}#}
                                <input type="time" class="form-control col-3 mr-1"
                                       name="tmp_maximo" placeholder="03:30" {% if areaComun.tmp_maximo.hour <= 9 %}value="0{{ areaComun.tmp_maximo.hour }}{% if areaComun.tmp_maximo.minute <= 9 %}:0{{ areaComun.tmp_maximo.minute }}:00">{% else %}:{{ areaComun.tmp_maximo.minute }}:00">{% endif %}{% else %}value="{{ areaComun.tmp_maximo.hour }}{% if areaComun.tmp_maximo.minute <= 9 %}:0{{ areaComun.tmp_maximo.minute }}:00">{% else %}:{{ areaComun.tmp_maximo.minute }}:00">{% endif %}
                                       {% endif %}
                            </div>

                            <div class="form-group row">
                                <label class="col-12 col-sm-4 col-form-label pl-0"
                                       for="">
                                    <strong><span class="text-danger">*</span> Estado
                                    </strong>
                                </label>

                                {% if areaComun.estado == "H" %}
                                    <div class="form-group contenedor-radio">
                                        <input class="" id="auto"
                                               type="radio" name="estado" value="H" checked>
                                        <label class="label-radio"
                                               for="auto">Habilitado</label>

                                        <input class="" id="pie"
                                               type="radio" name="estado" value="D">
                                        <label class="label-radio"
                                               for="pie">Deshabilitado</label>

                                        <input class="" id="bici"
                                               type="radio" name="estado" value="M">
                                        <label class="label-radio"
                                               for="bici">Mantenimiento</label>
                                    </div>
                                {% endif %}

                                {% if areaComun.estado == "D" %}
                                    <div class="form-group contenedor-radio">
                                        <input class="" id="auto"
                                               type="radio" name="estado" value="H">
                                        <label class="label-radio"
                                               for="auto">Habilitado</label>

                                        <input class="" id="pie"
                                               type="radio" name="estado" value="D" checked>
                                        <label class="label-radio"
                                               for="pie">Deshabilitado</label>

                                        <input class="" id="bici"
                                               type="radio" name="estado" value="M">
                                        <label class="label-radio"
                                               for="bici">Mantenimiento</label>
                                    </div>
                                {% endif %}

                                {% if areaComun.estado == "M" %}
                                    <div class="form-group contenedor-radio">
                                        <input class="" id="auto"
                                               type="radio" name="estado" value="H">
                                        <label class="label-radio"
                                               for="auto">Habilitado</label>

                                        <input class="" id="pie"
                                               type="radio" name="estado" value="D">
                                        <label class="label-radio"
                                               for="pie">Deshabilitado</label>

                                        <input class="" id="bici"
                                               type="radio" name="estado" value="M" checked>
                                        <label class="label-radio"
                                               for="bici">Mantenimiento</label>
                                    </div>
                                {% endif %}

                            </div>

                            <div class="row d-flex justify-content-end">
                                <button class="btn btn-success btn-lg mr-2" onclick="">Actualizar</button>
                                <button onclick="window.history.back();" class="btn btn-danger btn-lg" type="button">Cancelar</button>
                            </div>
                        </form>
                </fieldset>
            </div>
        </div>
    </div>

{% endblock %}

{% block extasjs %}
    <script src="{% static 'js/modal-propietario.js' %}"></script>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    <script src="{% static 'js/PreviewImagen.js' %}"></script>
{% endblock %}
{##}
{#{% if areaComun.disp_desde.hour <= 9 %}#}
{#    value="0{{ areaComun.disp_desde.hour }}#}
{#    {% if areaComun.disp_desde.minute <= 9 %}#}
{#        :0{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% else %}#}
{#        :{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% endif %}#}
{#{% else %}#}
{#    value="{{ areaComun.disp_desde.hour }}:0{{ areaComun.dip_hasta.minute }}"> A:#}
{#    {% if areaComun.disp_desde.minute <= 9 %}#}
{#        :0{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% else %}#}
{#        :{{ areaComun.disp_desde.minute }}"> A:#}
{#    {% endif %}#}
{#{% endif %}#}

templates/areaComun/eliminar_areaComun.html
{% extends 'base/base.html' %}

{% block title %}
ELIMINAR AREA COMUN
{% endblock %}

{% block style %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/formularios-style.css' %}">
{% endblock %}

{% block content %}
    <div class="container contenido-form">

        <div class="row d-flex justify-content-center mt-4 mb-5 animated bounceInLeft" id="formulario">
            <div class="col-12 col-sm-11 col-md-9 col-lg-7 col-xl-6">
                <fieldset>
                    <legend>Eliminar</legend>
                    <h3>Desea eliminar este Area Comun?</h3>

                        <form method="post">
                            {% csrf_token %}
                            <div class="row d-flex justify-content-center">
                                <img class="img-fluid img-thumbnail w-50 h-25" src="{{ areacomun.imagen.url }}" alt="No se pudo Cargar">
                            </div>

                             <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Categoria</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areacomun.get_categoria_display }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Nombre</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areacomun.nombre }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-12 col-md-4 col-form-label pl-0"
                                       for=""><strong>Sector :</strong></label>
                                <p class="col-sm-12 col-md-6 col-form-label pl-0">{{ areacomun.sector }}</p>
{#                                       data-toggle="tooltip" data-placement="right"#}
                            </div>

                            <button class="btn btn-danger" type="submit">Si, Eliminar</button>
                            <button type="button" onclick="window.history.back();" class="btn btn-primary">Cancelar</button>

                        </form>

                </fieldset>
            </div>
        </div>
    </div>
{% endblock %}

templates/areaComun/listar_areaComun.html
{% extends 'base/base.html' %}

{% block title %}
    LISTA DE AREA COMUN
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="../../static/css/formularios-style.css">
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1 class="text-center">Lista de Areas Comunes</h1>
        <a href="{% url 'areaComun:registrar_areaComun' %}"
           class="btn btn-dark btn-lg mb-2">Nueva Area</a>

        <div class="container">
            <div class="form-group row">
                <select name="" id="" class="form-control col-12 col-sm-3 col-md-2 p-0 mr-sm-1 mb-1">
                    <option value="nombre">Nombre Area</option>
                    <option value="app">Sector</option>
                    <option value="apm">Estado</option>
                </select>

                <input class="form-control col-12 col-sm-6 col-md-4 mr-sm-1" id="buscar" type="Buscar" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" onclick="inicio()">Buscar</button>
    {#                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
            </div>
        </div>

        <div class="row">
            <div class="table-responsive col-12">
                <table class="table table-striped table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr class="text-center">
                            <th nowrap="true" scope="col">Nro.</th>
                            <th nowrap="true" scope="col">Nombre</th>
                            <th nowrap="true" scope="col">Sector</th>
                            <th nowrap="true" scope="col">Disp. Desde</th>
                            <th nowrap="true" scope="col">Disp. Hasta</th>
                            <th nowrap="true" scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if areaComun %}
                        {% for areaComun in areaComun %}
                            <tr>
                                <th scope="row" class="text-center">{{ areaComun.id }}</th>
                                <td>{{ areaComun.nombre }}</td>
                                <td class="text-center">{{ areaComun.sector }}</td>
                                <td class="text-center">{{ areaComun.disp_desde }}</td>
                                <td class="text-center">{{ areaComun.dip_hasta }}</td>
                                <td nowrap="true" class="text-center">
                                    <a href="{% url 'areaComun:detalle_areaComun' areaComun.id %}" class="btn btn-info">Detalle</a>
                                    <a href="{% url 'areaComun:editar_areaComun' areaComun.id %}" class="btn btn-warning">Editar</a>
                                    <a href="{% url 'areaComun:eliminar_areaComun' areaComun.id %}" class="btn btn-danger"> Eliminar</a>
                                </td>
                            </tr>
                    {% endfor %}
                    {% else %}
                        <h2>No hay Areas Comunes Registradas!</h2>
                    {% endif %}
                    </tbody>
                </table>
            </div>

            <div class="d-flex flex-wrap justify-content-center">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"
                           class="btn btn-dark btn-lg mr-1">Anterior</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}"
                           class="btn btn-success btn-lg ml-1">Siguiente</a>
                    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}